echo "lui" |  bin/tc 
echo "addiu" |  bin/tc
echo "addu" |  bin/tc 
echo "and" |  bin/tc 
echo "and" |  bin/tc 
echo "andi" |  bin/tc  
echo "div" |  bin/tc 
echo "divu" |  bin/tc 
echo "mult" |  bin/tc 
echo "or" |  bin/tc 
echo "ori" |  bin/tc 
echo "xor" |  bin/tc 
echo "xori" |  bin/tc 
echo "subu" |  bin/tc 
